# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                 CachyOS Hyprland Configuration              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$mainMod = SUPER

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Source Files                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/windowrules.conf

# Modifying these configs can be done by creating a user defined config in the home directory, e.g.
## ~/.config/hypr/config/user-config.conf
# source = ~/.config/hypr/config/user-config.conf
# fix tooltips (always have a title of `win.<id>`)
windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$
windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^(win.*)$
# fix tab dragging (always have a single space character as their title)
windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^\\s$
windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^\\s$

exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent

exec-once = hyprsunset

exec-once = systemctl --user start hyprpolkitagent

exec-once = rm -f /tmp/ff-ws*.lock /tmp/ff-ws*.pid
