
# đường dẫn ảnh (preload trước để load nhanh)
preload = ~/Pictures/anh1.png
preload = ~/Pictures/anh2.png

# đặt wallpaper cho từng màn hình
wallpaper = eDP-1, ~/Pictures/anh1.png
wallpaper = HDMI-A-1, ~/Pictures/anh2.png

# tùy chọn khác (tùy chỉnh được)
splash = true
ipc = true
