# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Animations Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/Configuring/Animations/

# animations {
#     enabled = yes
#     bezier = overshot, 0.13, 0.99, 0.29, 1.1
#     animation = windowsIn, 1, 4, overshot, slide
#     animation = windowsOut, 1, 5, default, popin 60%
#     animation = border, 1, 5, default
#     animation = workspacesIn, 1, 6, overshot, slide
#     animation = workspacesOut, 1, 6, overshot, slidefade 80%
# }
animations {
    enabled = yes
    bezier = iPad, 0.22, 1, 0.36, 1
    animation = windows,    1, 4.2, iPad, popin 88%
    animation = border,     1, 10, iPad
    animation = workspaces, 1, 5,   iPad, slide
  animation = fade, 1, 6, iPad
}
